# Generated by Django 3.1.4 on 2020-12-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_date_posted_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
