# Generated by Django 3.1.4 on 2020-12-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201214_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
