# Generated by Django 3.1.4 on 2020-12-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201215_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='core.userdata'),
        ),
    ]
