# Generated by Django 3.1.4 on 2020-12-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201215_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='user',
        ),
    ]
