# Generated by Django 3.1.4 on 2020-12-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201215_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_posted_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
