# Generated by Django 3.1.4 on 2020-12-16 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_posted_comment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
