# Generated by Django 3.1.4 on 2020-12-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
