# Generated by Django 3.1.4 on 2020-12-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_set_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
