# Generated by Django 3.1.4 on 2020-12-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_authtoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
