# Generated by Django 3.1.4 on 2020-12-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_useraddres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddres',
            new_name='UserAddress',
        ),
    ]
