# Generated by Django 3.1.4 on 2020-12-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_useraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.TextField(max_length=50),
        ),
    ]
