# Generated by Django 3.1.4 on 2020-12-19 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20201218_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 19, 19, 31, 568201, tzinfo=utc)),
        ),
    ]
